### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mvz** [handlebars-lang/handlebars-parser#13]
Hi, I'm re-using some files from this project to create a Ruby implementation of handlebars, and I want to include proper license information for them. As I understand it, handlebars-parser was extracted from handlebars-js, which is under the MIT license. However, this project has the ISC license according to package.json and includes no author info there. Is this license info correct?

**Comment by jaylinski** [comment]
The original author of the commit with the license info isn't on GitHub anymore it seems:

https://github.com/handlebars-lang/handlebars-parser/commit/706c6ff670053cd956a0c6d9ce64474bd2d73e64#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

So it's hard to tell if the default `npm init` license (ISC) was used because it's default or it was chosen deliberately.

> Is this license info correct?

Yes, it is correct. We may change it to MIT later (they are pretty similar anyway).

**Comment by mvz** [comment]
Thanks, @jaylinski!
